# 
language: r
# Versions of R to build on
r:
  - oldrel
  - release
  - devel

# Operating systems to build on 
os:
  - linux
  - osx

# Linux options
sudo: false
dist: trusty
cache: packages

# 1. Apparently R-devel for OSX is a pain on most CI platforms, so I'm excluding
# it from our builds. See below for more details on the problem
# https://community.rstudio.com/t/r-devel-error-on-travis-ci-and-appveyor/2708
# moreover, I am excluding R-oldrel for osx, and testing it using intalling
# libgit2 through brew_packages.
matrix:
  exclude:
  - os: osx
    r: 
      - devel
      - oldrel
  include:
    os: osx
    osx_image: xcode8
    brew_packages: libgit2
    
notifications:
  email:
    - levisc8@gmail.com
    - brad.ochocki@gmail.com 
    - aldo.compagnoni@gmail.com  

# safelist
branches:
  only:
  - master
  - api

script: 
  - |
    R CMD build .
    travis_wait 40 R CMD check popler*.tar.gz

after_success:
  - travis_wait 40 Rscript -e 'covr::codecov()'

