# 
language: r
# Versions of R to build on
r:
  - oldrel
  - release
  - devel

# Operating systems to build on 
os:
  - linux
  - osx

# Linux options
sudo: false
dist: trusty
cache: packages

# Apparently R-devel for OSX is a pain on most CI platforms, so I'm excluding
# it from our builds. See below for more details on the problem
# https://community.rstudio.com/t/r-devel-error-on-travis-ci-and-appveyor/2708
matrix:
  exclude:
  - os: osx
    r: devel
    
notifications:
  email:
    - levisc8@gmail.com
    - brad.ochocki@gmail.com 
    - aldo.compagnoni@gmail.com  
    
script: 
  - |
    R CMD build .
    travis_wait 30 R CMD check popler.tar.gz
    
after_success:
  - Rscript -e 'covr::codecov()'

